### ISSUE TITLE
Plugin Import Error

### ISSUE THREAD

**Issue by dvdmtw98** [ObsidianPublisher/mkdocs-custom-tags-attributes#1]
After adding the plugin in the plugin section and mentioning the CSS file in the extra_css section the plugin fails to be detected be mkdocs

### Mkdocs YAML File

![image](https://user-images.githubusercontent.com/31100937/205319068-c67375a2-5b4d-44fd-840b-746fa3e41f84.png)
![image](https://user-images.githubusercontent.com/31100937/205319103-1cfbf584-c55d-4045-b022-238e3c9fdc18.png)

### Mkdocs Output

![image](https://user-images.githubusercontent.com/31100937/205319169-f7dc178e-0116-468b-827e-8f7bcf1348b6.png)

The plugin was installed using the following command;
`pip install mkdocs-custom-tags-attributes`

#### Additional Information
Python 3.9.13
Windows 11 (22H2)

**Comment by Lisandra-dev** [comment]
Could you please share the `mkdocs.yml` file ? 

I think you must have search in the first lines.

I can't repro the issue in my environment.

**Comment by dvdmtw98** [comment]
Thanks. Now the issue is fixed.

I think I should start a new thread for this but does custom-tag-attributes support tags that have `-` in them ?
I have a few tags that have the pattern: `#azure-compute`, `#azure-serverless` any way I could style these tags
