### ISSUE TITLE
same #tag twice in one line doesn't work

### ISSUE THREAD

**Issue by daxcore** [ObsidianPublisher/mkdocs-custom-tags-attributes#4]
if the same tag is used in one line twice or more, just the first one will be replaced.

**Comment by Mara-Li** [comment]
yes, it's know and won't be fixed. It's a limitation of the algorithm, and I have too much difficulty to maintain it, so I won't fix edge case.

**Comment by daxcore** [comment]
just removing the 1 in plugin.py line 108 does the trick for me. is there a special reason for the 1?

```diff
- line = line.replace(tag, ial, 1)
+ line = line.replace(tag, ial)
```

**Comment by Mara-Li** [comment]
Maybe it is a artefact from old version/tests. 
I can remove it, but in same times, I have the fear to create more bugs T-T
